config/routes.rb
Rails.application.routes.draw do
  #get 'sessions/new'
  resources :sessions, only: [:new, :create, :destroy]

  root 'tops#index'

  resources :users

  resources :pictures do
    collection do
      #【新規登録前のデータ確認用画面】へのルートを追加
      post :confirm
    end

    member do
      #【更新前のデータ確認用画面】へのルートを追加
      post :edit_confirm

      #【ユーザーごとのインデックス画面】へのルートを追加
      get :user_index
    end
  end
end

app/views/layouts/_form_msgerr.html.erb
<!--↓エラーメッセージ表示枠-->
<% if model_info.errors.any? %>
  <div id="error_explanation">
    <h2 class="err_msg"><%= get_tablename_by_model(model_info) %>
      情報登録で<%= pluralize(model_info.errors.count, "個") %> のエラーが発生しています。</h2>
    <ul>
    <% model_info.errors.full_messages.each do |message| %>
      <li class="err_msg"><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FaceClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="container" id="MainContainer">

    <header class="clearfix">

      <div class="box_title_head">
        <%= yield :show_head_title %>
      </div>

      <div class="box_btn_head">
        <% if logged_in? %>
          <!-- ログインしている場合-->

          <%= link_to "プロフィール" ,user_path(current_user.id) ,
          class: "btn btn-default " %>
          <%= link_to "ログアウト" ,session_path(current_user.id), method: :delete ,
          class: "btn btn-default " %>

        <% else  %>
          <!-- ログインしていない場合-->
          <%= link_to "ユーザー登録" ,new_user_path ,class: "btn btn-default btn_head" %>
          <%= link_to "ログイン" ,new_session_path ,class: "btn btn-default btn_head" %>

        <% end  %>
      </div>

    </header>

    <!-- 登録前、バリデーションに引っかかったときなどのメッセージ表示-->
    <!-- ……エラー内容が格納されている変数を改めて投げる必要があるので、-->
    <!--yieldで各画面から改めて「layouts/form_msgerr」を呼び出す-->
    <%= yield :show_msgerr %>

    <!-- メッセージ表示-->
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key} err_msg") %>
    <% end %>

    <div class="main_content">
      <%= yield %>
    </div>

    <footer>
      <div class="box_btn_foot">
        <%= link_to 'アプリ選択画面へ戻る', root_path , class: "btn btn-default btn_foot" %>
    </div>
    </footer>

  </div>

</html>